# ============================================
# Perfil Oracle Cloud (ATP)
# ============================================

# 1. URL de conexión (Corregido: alias unimatchdb)
spring.datasource.url=jdbc:oracle:thin:@unimatchdb_high?TNS_ADMIN=C:/Users/luisa/OneDrive/Escritorio

# 2. Credenciales
spring.datasource.username=ADMIN
spring.datasource.password=DatabaseUnimatch08

# 3. Configuración técnica
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

# Servir el frontend (Ubicación estándar)
spring.web.resources.static-locations=classpath:/static/
